version: "3.8"
services:
  api:
    build:
      context: ./api/
      target: gobuilder
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - db
    command: [ "./run.sh" ]
    networks:
      - message-board-network
  
  db:
    image: postgres:11.9
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - message-board-network

  front:
    build:
      context: ./front
    tty: true
    working_dir: /app
    volumes:
      - ./front:/app
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    ports:
      - 3000:3000
    command: bash -c 'yarn install && yarn dev'
    networks:
      - message-board-network

networks:
  message-board-network:
    driver: bridge

