openapi: 3.0.0
info:
  version: "0.0.1"
  title: "message-board"
servers:
  - url: "http://localhost:8080"
    description: local
tags:
  - name: "user"
    description: ユーザ
paths:
  /users:
    get:
      tags:
        - user
      operationId: GetUsers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
    post:
      tags:
        - user
      operationId: CreateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserParam"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                title: 作成されたユーザー
                $ref: "#/components/schemas/User"
        500:
          description: Internal Server Error
components:
  schemas:
    UserProp:
      type: object
      properties:
        name:
          type: string
          example: さとうだいき
        email:
          type: string
          example: daiki.sato@example.com
      required:
        - name
        - email
    User:
      type: object
      allOf:
      - properties:
          id:
            type: integer
            x-go-type: uint64
            example: 1
        required:
          - id
      - $ref: "#/components/schemas/UserProp"
    Users:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"
      required:
        - users
    CreateUserParam:
      $ref: "#/components/schemas/UserProp"

