// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xSPW/UQBD9K9FA6bN9fCnaCoEo0iEhKnTFxp7cbbB3ltm5KNHJhQmio6SnQvwCKv7N",
	"/hE0a+fgjoIm1Y5m5703+97uoKE+kEcvEcwOYrPB3ubyJaMVfBuRX1u2vbYeMl6AgQfVH1A1IyodhKGA",
	"fJodBKaALA4zGfbWdbm4tn3oEAy01r13ZbRCz+dm2VAPBchN0Pso7PxaKV17gFzuR5wXXCNDAdeLNS3m",
	"7tZ5efZEgd72eCiaxq9p/JHGz2n8lsZPafzyr+BQAOOHrWNswbxT9ZmpmJ+x2kPo/BIbgUExzl+QiomT",
	"LNVjjHaNi3OyrBRXyNGRBwN1WZdL3Y8CehscGHhc1mUNBQQrm2xYtY3IuQoURU+104ojf9aC+SsdmNbF",
	"KC+ovdHJhrygzyAbQueaDKsuo6rfZfy/PI/jH4bJmBjIxynUR/Xy3uSm76MSLcaGXZDJq2mNVt16WtfK",
	"cnh/5gXZ2+7kDfIV8skrZuKcodh11PzUSFhl6phntHtM01FjOyhgyx0Y2IgEU1W5uaEo5rQ+rWFY7UmP",
	"4en2e7r9lT7+vPsqZpIdVsPvAAAA//9HfpaNYgMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
