// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package openapi

// CreateUserParam defines model for CreateUserParam.
type CreateUserParam UserProps

// Id defines model for Id.
type Id uint64

// UpdateUserParam defines model for UpdateUserParam.
type UpdateUserParam UserProps

// User defines model for User.
type User struct {
	// Embedded fields due to inline allOf schema
	Id Id `json:"id"`
	// Embedded struct due to allOf(#/components/schemas/UserProps)
	UserProps `yaml:",inline"`
}

// UserProps defines model for UserProps.
type UserProps struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// Users defines model for Users.
type Users struct {
	Users []User `json:"users"`
}

// UserId defines model for UserId.
type UserId Id

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody CreateUserParam

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody UpdateUserParam

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

