// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi

// CreateUserParam defines model for CreateUserParam.
type CreateUserParam = User

// User defines model for User.
type User struct {
	Email string `json:"email"`
	Id    uint64 `json:"id"`
	Name  string `json:"name"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody = CreateUserParam

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserJSONBody
