// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"message-board/controller"
	"message-board/infrastructure/postgres"
	"message-board/router"
	"message-board/usecase"
)

// Injectors from wire.go:

func InitRouter(e *echo.Echo, db postgres.DB) *router.Router {
	iRepository := postgres.NewUserRepository(db)
	iUserUsecase := usecase.NewUser(iRepository)
	controllerController := controller.NewController(iUserUsecase)
	routerRouter := router.NewRouter(e, controllerController)
	return routerRouter
}

// wire.go:

var Set = wire.NewSet(postgres.Set, usecase.Set, controller.NewController, router.NewRouter)
